modLoader="javafml"
loaderVersion="[31,)"
logoFile="logo.png"
authors="Farcr & Bagel"
credits="Musicano, Ilja, & Pugz"

[[mods]]
    modId="swampexpansion"
    version="${file.jarVersion}"
    displayName="Swamp Expansion"
    description='''
    Expanding the Swamps. New wood, new blocks, new friends.
    '''

[[dependencies.swampexpansion]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.swampexpansion]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[1.0.0,)"
    ordering="AFTER"
    side="BOTH"